table _Measures
	lineageTag: 0e89a391-4db2-4748-8a88-36eab5cbf27c

	measure 'Volume Total Financiado' = SUM('public vw_lending_club_powerbi'[emprestimo_real])
		formatString: \$#,0.000;(\$#,0.000);\$#,0.000
		lineageTag: 1b3c4dac-bb26-4702-801a-f96d9b32b06b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Perda de Capital' =
			
			CALCULATE(
			    SUM('public vw_lending_club_powerbi'[emprestimo_real]),
			    'public vw_lending_club_powerbi'[loan_status] IN { "Charged Off", "Default" }
			)
		formatString: \$#,0.000;(\$#,0.000);\$#,0.000
		lineageTag: 31567610-9c28-4b98-aab7-ffa114a38223

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Taxa de Inadimplência Vol' =
			
			DIVIDE(
			    [Perda de Capital],
			    [Volume Total Financiado],
			    0
			)
		lineageTag: d01adbfe-0efa-4551-95df-8943ee88e7d3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Resultado Financeiro Liquido' = SUM('public vw_lending_club_powerbi'[resultado_financeiro_real])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0cbfe649-7ff7-4698-a1d1-a69a24801c61

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'ROA (Return on Assets) Acumulado' =
			
			DIVIDE(
			    [Resultado Financeiro Liquido],
			    [Volume Total Financiado],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bf30f9c5-de2a-455c-b010-c23d269f9b2a

	measure 'Resultado Financeiro Anualizado' = ```
			
			SUMX(
			    'public vw_lending_club_powerbi',
			    VAR _AnosContrato = IF(CONTAINSSTRING('public vw_lending_club_powerbi'[term], "36"), 3, 5)
			    RETURN 
			    DIVIDE('public vw_lending_club_powerbi'[resultado_financeiro_real], _AnosContrato)
			)
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 989c7fa7-91f3-442e-9776-e78a1355c80b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'ROA (Return on Assets) Anualizado' =
			
			DIVIDE(
			    [Resultado Financeiro Anualizado],
			    [Volume Total Financiado],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 44af7189-ffa2-4a42-8977-6a51babe0070

	measure 'Quantidade de Contratos' = DISTINCTCOUNT('public vw_lending_club_powerbi'[id])
		formatString: 0
		lineageTag: 1a81df78-e957-467b-a316-22c1ee5a345f

	measure 'Ticket Médio de Concessão' =
			
			DIVIDE(
			    [Volume Total Financiado],
			    [Quantidade de Contratos],
			    0
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b9998990-08a8-4f01-ab03-06769d8e265b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Ticket Médio Retorno Anualizado' =
			
			DIVIDE(
			    [Resultado Financeiro Anualizado],
			    [Quantidade de Contratos],
			    0
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d486079e-4f77-4b4a-ad9b-97f0a154bf6b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Custo de Oportunidade Total Anualizado' =
			
			VAR _Hurdle = 0.04
			RETURN
			    SUMX(
			        SUMMARIZE(
			            'public vw_lending_club_powerbi',
			            'public vw_lending_club_powerbi'[grade],
			            'public vw_lending_club_powerbi'[term],
			            'public vw_lending_club_powerbi'[faixa_comprometimento],
			            'public vw_lending_club_powerbi'[classe_renda]
			        ),
			        VAR _Esperado = [Volume Total Financiado] * _Hurdle
			        VAR _Real = [Resultado Financeiro Anualizado]
			        VAR _Diferenca = _Esperado - _Real
			        RETURN
			            IF(_Diferenca > 0, _Diferenca, 0)
			    )
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 87352be2-0381-4815-9596-70a799c7caa1

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Custo de Oportunidade Total Acumulado' =
			
			VAR _Hurdle = 0.04
			RETURN
			    SUMX(
			        SUMMARIZE(
			            'public vw_lending_club_powerbi',
			            'public vw_lending_club_powerbi'[grade],
			            'public vw_lending_club_powerbi'[term],
			            'public vw_lending_club_powerbi'[faixa_comprometimento],
			            'public vw_lending_club_powerbi'[classe_renda]
			        ),
			        VAR _AnosContrato = IF(CONTAINSSTRING('public vw_lending_club_powerbi'[term], "36"), 3, 5)
			        VAR _EsperadoAnual = [Volume Total Financiado] * _Hurdle
			        VAR _RealAnual = [Resultado Financeiro Anualizado]
			        VAR _DiferencaAnual = _EsperadoAnual - _RealAnual
			        VAR _PerdaAcumulada = _DiferencaAnual * _AnosContrato
			        RETURN
			            IF(_PerdaAcumulada > 0, _PerdaAcumulada, 0)
			    )
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 658c9f96-d8ec-459d-8221-ed23dda0d7c1

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition _Measures = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

