table _Measures
	lineageTag: 0e89a391-4db2-4748-8a88-36eab5cbf27c

	measure 'Volume Total Financiado' = SUM('public vw_lending_club_powerbi'[emprestimo_real])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 1b3c4dac-bb26-4702-801a-f96d9b32b06b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Perda de Capital' =
			
			CALCULATE(
			    SUM('public vw_lending_club_powerbi'[emprestimo_real]),
			    'public vw_lending_club_powerbi'[loan_status] IN { "Charged Off", "Default" }
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 31567610-9c28-4b98-aab7-ffa114a38223

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Taxa de Inadimplência Vol' =
			
			DIVIDE(
			    [Perda de Capital],
			    [Volume Total Financiado],
			    0
			)
		lineageTag: d01adbfe-0efa-4551-95df-8943ee88e7d3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Resultado Financeiro Liquido' = SUM('public vw_lending_club_powerbi'[resultado_financeiro_real])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 0cbfe649-7ff7-4698-a1d1-a69a24801c61

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'ROI do Portfolio' =
			
			DIVIDE(
			    [Resultado Financeiro Liquido],
			    [Volume Total Financiado],
			    0
			)
		lineageTag: bf30f9c5-de2a-455c-b010-c23d269f9b2a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition _Measures = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

