table 'public vw_lending_club_powerbi'
	lineageTag: e2f17175-0470-4826-8035-5cfae58fc6fb

	column id
		dataType: string
		lineageTag: 813c2074-ee51-4d9e-a9b6-0658b262b60f
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column loan_status
		dataType: string
		lineageTag: b6d9cee1-2c6d-429b-8059-c099ec8fb923
		summarizeBy: none
		sourceColumn: loan_status

		annotation SummarizationSetBy = Automatic

	column term
		dataType: string
		lineageTag: 2db4993c-27db-498c-b8ac-fa405bf007c2
		summarizeBy: none
		sourceColumn: term

		annotation SummarizationSetBy = Automatic

	column home_ownership
		dataType: string
		lineageTag: 601b8d53-05a9-4eb4-b4ce-d0e2dbe3dbe5
		summarizeBy: none
		sourceColumn: home_ownership

		annotation SummarizationSetBy = Automatic

	column grade
		dataType: string
		lineageTag: c922ba5a-bded-43d6-9a87-8c39c373dc88
		summarizeBy: none
		sourceColumn: grade

		annotation SummarizationSetBy = Automatic

	column sub_grade
		dataType: string
		lineageTag: 289d1cb5-1a13-459e-aae9-fa80f9b01f6b
		summarizeBy: none
		sourceColumn: sub_grade

		annotation SummarizationSetBy = Automatic

	column purpose
		dataType: string
		lineageTag: cda967c0-3a65-42e1-85c1-85790fdaa9a7
		summarizeBy: none
		sourceColumn: purpose

		annotation SummarizationSetBy = Automatic

	column emp_length
		dataType: string
		lineageTag: 6c46dfaf-e120-4cbe-bcee-7a2235e26a6b
		summarizeBy: none
		sourceColumn: emp_length

		annotation SummarizationSetBy = Automatic

	column verification_status
		dataType: string
		lineageTag: 6d33fb84-6a2e-4f14-8da1-af87d4ffce2a
		summarizeBy: none
		sourceColumn: verification_status

		annotation SummarizationSetBy = Automatic

	column addr_state
		dataType: string
		lineageTag: ad52b523-aad0-4af7-b35f-c182e23cde38
		summarizeBy: none
		sourceColumn: addr_state

		annotation SummarizationSetBy = Automatic

	column data_emissao
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3c156705-d340-41a2-a045-6978577ec864
		summarizeBy: none
		sourceColumn: data_emissao

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ano_emissao
		dataType: int64
		formatString: 0
		lineageTag: 060ac7c0-1677-4706-a6a6-5a16800f7794
		summarizeBy: sum
		sourceColumn: ano_emissao

		annotation SummarizationSetBy = Automatic

	column classe_renda
		dataType: string
		lineageTag: e78f85f8-30b8-4666-8036-66315f674e28
		summarizeBy: none
		sourceColumn: classe_renda

		annotation SummarizationSetBy = Automatic

	column faixa_comprometimento
		dataType: string
		lineageTag: 95356a7e-d5e0-41e8-84fc-528d5c25cd69
		summarizeBy: none
		sourceColumn: faixa_comprometimento

		annotation SummarizationSetBy = Automatic

	column renda_real
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: d4cef64e-3984-4713-8cca-b82f1bd71299
		summarizeBy: sum
		sourceColumn: renda_real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column emprestimo_real
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 69ed866e-896d-4c72-8d07-e4ddba230da9
		summarizeBy: sum
		sourceColumn: emprestimo_real

		annotation SummarizationSetBy = Automatic

	column resultado_financeiro_real
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 71f964b9-3162-4100-a032-436734b8a642
		summarizeBy: sum
		sourceColumn: resultado_financeiro_real

		annotation SummarizationSetBy = Automatic

	partition 'public vw_lending_club_powerbi' = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("localhost", "lending_club_db"),
				    public_vw_lending_club_powerbi = Fonte{[Schema="public",Item="vw_lending_club_powerbi"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(public_vw_lending_club_powerbi,{{"renda_real", Currency.Type}, {"emprestimo_real", Currency.Type}, {"resultado_financeiro_real", Currency.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

